### PR TITLE
Fix Mareanie game point

### PR DESCRIPTION
**Pull request by enumag**
You need waterfall to reach it meaning Terra's badge is required.

### CODE REVIEW

**Comment by brentspector** [comment]
Thanks @enumag ! I appreciate the help

**Comment by brentspector** [comment]
Let me know if you need the Android app version working. It's currently behind because merges don't automatically increment the version number, which caused the upload to fail.

**Comment by enumag** [comment]
I am an android user, yes. But this is just minor fix, doesn't matter if it lands now or later.

**Comment by brentspector** [comment]
New android version has been pushed, but still going through reviews. The update should be available once that's complete, and should be available through the normal update procedure for your phone.

**Pull request merged**
